
name: flutter_scope
version: 0.1.0-beta.2
homepage: https://github.com/LoveCommunity/flutter_scope
description: A declarative dependency injection library which use dart syntax and flutter style

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  dart_scope: ^0.1.0-beta.3
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.21.4
