
name: flutter_scope
version: 0.1.0-alpha.1
homepage: https://github.com/LoveCommunity/flutter_scope

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  dart_scope: ^0.1.0-alpha.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  test: ^1.19.5
