
name: flutter_scope
version: 0.1.0-alpha.2
homepage: https://github.com/LoveCommunity/flutter_scope
description: A declarative dependency injection library which use dart syntax and flutter style

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  dart_scope: ^0.1.0-beta.1

dependency_overrides:
  dart_scope:
    git: 
      url: "git@github.com:LoveCommunity/dart_scope.dart.git"
      ref: "experiment/observable/hotreload/equality"
    
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  test: ^1.19.5
